config/routes.rb
Classroom::Application.routes.draw do

  match "class_rooms/:id/plus1" => "class_rooms#plus1", :as => :class_rooms_plus1, :via => :post
  
  match "class_rooms/:id/minus1" => "class_rooms#minus1", :as => :class_rooms_minus1, :via => :post

  get "class_rooms/class_names"
  
  get "students/show"
 
  get "class_rooms/search"

  match '/auth/:provider/callback' => 'authentications#create'

  get "authentications/index"

  get "authentications/create"

  get "authentications/destroy"

  match 'activate(/:activation_code)' => "activations#create", :as => :activate_account
 
  get "users/edit_password"
  
  get "users/resend_activation"
  
  resources :password_resets
  
  match 'password_resets/:id/please_register' => "password_resets#please_register", :as => :resend
  
  resources :users do
    match 'notifications/count' => 'notifications#count'
    resources :notifications
  end

  post "class_rooms/add_user"
  
  get "class_rooms/del_user"
  
  resources :user_permissions
  
  match 'class_rooms/:id/students' => "class_rooms#students", :as => :class_room_students

  resources :class_rooms do
    resources :premium_classes
    resources :announcements do
    end
    resources :resource_pages do
      resources :sections do
        resources :resources do
          resources :resource_comments
          match 'documents/:id/create_doc_rec' => "documents#create_doc_rec", :as => :doc_rec, :via => :post
        end
        match 'resources/:id/change_hidden' => "resources#change_hidden", :as => :publish
        match 'resources/:id/change_completed' => "resources#change_completed", :as => :completed
        match 'resources/:id/change_order' => "resources#change_order", :as => :rearrange
      end
      match 'sections/:id/change_order' => "sections#change_order", :as => :rearrange
      match 'sections/:id/update' => "sections#update", :as => :update, :via => :post
    end
    match 'forums/:id/search_by_tag' => "forums#search_by_tag", :as => :search_by_tag, :via => :get 
    match 'forums/:id/search' => "forums#search", :as => :search, :via => :get 
    resources :forums do
      resources :posts do
        match "comments/:id/plus1" => "comments#plus1", :as => :comments_plus1, :via => :post
        match "comments/:id/minus1" => "comments#minus1", :as => :comments_minus1, :via => :post
        resources :comments do
          resources :subcomments
        end
      end
    end
  end
  
  match 'class_rooms/:id/change_active' => "class_rooms#change_active", :as => :activate
  match 'class_rooms/:id/begin_class' => "class_rooms#begin_class", :as => :begin
  
  resources :authentications

  

  get "user_sessions/new"
  
  get "user_sessions/new_ajax"
  
  get "home/teacher_index"
  
  get "home/index"
  
  get "home/manage"

  get "home/please_register"

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'login_ajax' => "user_sessions#new_ajax",      :as => :login_ajax
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  get "auth/facebook"
 
  resources :pages, :only => :show

  root :to => 'home#index'

  

end

app/models/resource_page.rb
class ResourcePage < ActiveRecord::Base
  validates :section, :presence => true

  belongs_to :class_room
  has_many :sections, :dependent => :destroy
  has_many :resources, :through => :sections
  
  SECTIONS = ['lessons', 'homework', 'materials', 'quizzes']
end

app/controllers/resource_pages_controller.rb
class ResourcePagesController < ApplicationController
  def show
    @class_room = ClassRoom.find(params[:class_room_id])
    require_enrolled(@class_room)
  	if is_enrolled(@class_room)
  	  @resource_page = ResourcePage.find(params[:id])
      @sections = @resource_page.sections.sort_by { |sec| sec.order }
  	  errors = flash[:errors]
  	  @resource = Resource.new
  	  @resource.hidden = 1
  	  @section = Section.new
  	  set_vars
      respond_to do |format|
        format.html { render :layout => "show_class_room", :locals => {:which_tab => @resource_page.section} }
        format.json { render json: @class_room }
  	  end
    end
  end
end

app/views/resource_pages/show.html.haml
%h2.resource_page_title= @resource_page.section

-if @is_creator
  :javascript
    allow_draggable = true
  
  .admin_edit
    - if @resource.errors.any?
      #error_explanation
      %h2 #{pluralize(@resource.errors.count, "error")} prohibited your new item from being saved:

      %ul
      - @resource.errors.full_messages.each do |msg|
        %li= msg   
    .upload_box
      .title
        Add new #{@resource_page.section.singularize}:
        %span{:class => "upload_links " + (@resource.errors.any? ? "javascript_show" : ""),
              :style => @resource.errors.any? ? "display: none" : ""}
          %a{:href => "#", :id => "resource_upload"} Upload File
          |
          %a{:href => "#", :id => "resource_link"} Paste Link
          |
          %a{:href => "#", :id => "resource_document"} Write New Document
          
 

      %div{:class => "add_resource_form " + (@resource.errors.any? ? "" : "no_javascript") }
        = render :partial => "resources/form",
          :locals => { :style => "small_resource_form"}
       
-if @resource_page.section.downcase == "homework" and not @is_creator
  %p{:style=>"margin: 10px 0; color: #444; font-size: .9em;"} Use the checkboxes to keep track of the work you've finished.

%ul.list_of_sections
  - @sections.each do |section|  
    %li.materials_section
      %h3 
        %span.name= section.title
        - if @sections.length > 1 && @is_creator
          = link_to "delete", [@class_room, @resource_page, section], 
            :confirm => "Are you sure you want to delete this section? This will delete all #{@resource_page.section} associated with this section.  Move them to a different section if you want to keep them.", 
            :method => :delete, :class => "delete_section_link"
        - if @is_creator
          %a{:class => "rename_section_link"} rename

      -if @is_creator
        = form_for section, :url => class_room_resource_page_rearrange_path(@class_room, @resource_page, section) do |f|
          .field
            = label_tag :section, :Location, :class => "main"
            = text_field(:section, :order)
          = f.submit "Change order"
        .rename_section_form_container
          = form_for section, :url => class_room_resource_page_update_path(@class_room, @resource_page, section) do |f|
            .field
              = f.label :section_title, :class => "main"
              = f.text_field :title, :class => "text"
            = f.submit "Change Section Name"
      - resources = section.resources
      %ul.lists_to_connect{:id => "section-" + section.id.to_s}
        - if resources.length > 0
          - resources = resources.sort_by { |res| res.order }
          - resources.each do |resource|
            - if !resource.hidden || @is_creator
              %li{:id => "resource-" + resource.id.to_s, :class => (resource.hidden ? "hidden" : "") + (resource.users.include?(@user)?"completed" : "")}
                .resource_list_name 
                  =link_to "#{resource.name}", class_room_resource_page_section_resource_path(@class_room, @resource_page, section, resource)
                  %span.hidden_indicator= "(hidden)" if resource.hidden
                  %span.resource_list_timestamp
                    posted #{time_ago_in_words resource.created_at} ago
                    - if @is_creator
                      = link_to 'edit', edit_class_room_resource_page_section_resource_path(@class_room, @resource_page, section, resource)
                      = link_to resource.hidden ? "publish" : "hide", class_room_resource_page_section_publish_path(@class_room, @resource_page, section, resource), :class => "hide_link"
                      - if resource != @class_room.resource
                        = link_to 'delete', class_room_resource_page_section_resource_path(@class_room, @resource_page, section, resource), confirm: "Are you sure you want to destroy this file?", method: :delete
                    - if resource.source_call == "Homework" && !@is_creator
                      = link_to resource.users.include?(@user) ? "mark as uncompleted" : "mark as completed", class_room_resource_page_section_completed_path(@class_room, @resource_page, section, resource), :class => "homework_completed_link"

                  - if @is_creator
                    = form_for resource, :url => class_room_resource_page_section_rearrange_path(@class_room, @resource_page, section, resource) do |f|
                      .field
                        = label_tag :resource, :Section, :class => "main"
                        = collection_select(:section, :id, @sections, :id, :title)
                        -# want to get resources from the selected section before submitting :/
                      .field
                        = label_tag :resource, :Location, :class => "main"
                        = text_field(:resource, :order)
                      = f.submit "Change order"
                .resource_list_info #{resource.caption}
-if @is_creator
  .add_new_section
    = form_for [@class_room, @resource_page, @section]  do |f|
      - if @section.errors.any?
        #error_explanation
          %h2 #{pluralize(@section.errors.count, "error")} prohibited your new item from being saved:

          %ul
          - @section.errors.full_messages.each do |msg|
            %li= msg
      = f.text_field :title, :class => "text"  
      = f.submit "Add New Section"
  %p Teacher Tip: Drag #{@resource_page.section.downcase} and sections to reorder them.