config/routes.rb
Classroom::Application.routes.draw do

  match "class_rooms/:id/plus1" => "class_rooms#plus1", :as => :class_rooms_plus1, :via => :post
  
  match "class_rooms/:id/minus1" => "class_rooms#minus1", :as => :class_rooms_minus1, :via => :post

  get "class_rooms/class_names"
  
  get "students/show"
 
  get "class_rooms/search"

  match '/auth/:provider/callback' => 'authentications#create'

  get "authentications/index"

  get "authentications/create"

  get "authentications/destroy"

  match 'activate(/:activation_code)' => "activations#create", :as => :activate_account
 
  get "users/edit_password"
  
  get "users/resend_activation"
  
  resources :password_resets
  
  match 'password_resets/:id/please_register' => "password_resets#please_register", :as => :resend
  
  resources :users do
    match 'notifications/count' => 'notifications#count'
    resources :notifications
  end

  post "class_rooms/add_user"
  
  get "class_rooms/del_user"
  
  resources :user_permissions
  
  match 'class_rooms/:id/students' => "class_rooms#students", :as => :class_room_students

  resources :class_rooms do
    resources :premium_classes
    resources :announcements do
    end
    resources :resource_pages do
      resources :sections do
        resources :resources do
          resources :resource_comments
          match 'documents/:id/create_doc_rec' => "documents#create_doc_rec", :as => :doc_rec, :via => :post
        end
        match 'resources/:id/change_hidden' => "resources#change_hidden", :as => :publish
        match 'resources/:id/change_completed' => "resources#change_completed", :as => :completed
        match 'resources/:id/change_order' => "resources#change_order", :as => :rearrange
      end
      match 'sections/:id/change_order' => "sections#change_order", :as => :rearrange
      match 'sections/:id/update' => "sections#update", :as => :update, :via => :post
    end
    match 'forums/:id/search_by_tag' => "forums#search_by_tag", :as => :search_by_tag, :via => :get 
    match 'forums/:id/search' => "forums#search", :as => :search, :via => :get 
    resources :forums do
      resources :posts do
        match "comments/:id/plus1" => "comments#plus1", :as => :comments_plus1, :via => :post
        match "comments/:id/minus1" => "comments#minus1", :as => :comments_minus1, :via => :post
        resources :comments do
          resources :subcomments
        end
      end
    end
  end
  
  match 'class_rooms/:id/change_active' => "class_rooms#change_active", :as => :activate
  match 'class_rooms/:id/begin_class' => "class_rooms#begin_class", :as => :begin
  
  resources :authentications

  

  get "user_sessions/new"
  
  get "user_sessions/new_ajax"
  
  get "home/teacher_index"
  
  get "home/index"
  
  get "home/manage"

  get "home/please_register"

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'login_ajax' => "user_sessions#new_ajax",      :as => :login_ajax
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  get "auth/facebook"
 
  resources :pages, :only => :show

  root :to => 'home#index'

  

end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base  
  validates :name,  :presence => true
  #validates :occupancy, :presence => true
  #validates :price, :presence => true
  #validates_numericality_of :price
  #validates_numericality_of :occupancy
  validates :start_date, :presence => true
  validates :category, :presence => true
  #validates :end_date, :presence => true
  validates :tag_line, :length => { :maximum => 150 }
  
  has_many :user_permissions
  has_many :users, :through => :user_permissions
  
  has_many :resource_pages, :dependent => :destroy
  has_many :sections, :through => :resource_pages
  has_many :resources
  
  has_many :announcements, :dependent => :destroy
  
  has_many :class_room_ratings
  
  has_one :forum, :dependent => :destroy
  
  has_one :premium_class, :dependent => :destroy

  belongs_to :resource, :foreign_key => "description_id"

  belongs_to :user
  
  # never change these names, or the order, ever :D
  CATEGORIES = [ 'All', 'Humanities', 'Science', 'Math/Engineering', 'Music', 'Entertainment', 'Athletics', 'Life Skills', 'Other' ]  
  
  
  def rating
    return self.class_room_ratings.sum(:value)
  end
  
  def rating_by_user(user_id)
    a = ClassRoomRating.where("user_id = ? AND class_room_id = ?", user_id, self.id).first
    if a
      return a.value
    else
      return 0
    end
  end
  
  def self.search(search, category)
    @result = []
    @ids = []
    if search == nil && category == nil
      return @result
    elsif(category == nil && search == "")
      return ClassRoom.all
    elsif search == "" || search == nil
      return ClassRoom.where('category = ?', category)
    else
			tokenize = search.scan(/"[^"]*"|[^"'\s]+/)
			tokenize = tokenize.map {|x| '%' + x.strip.gsub(/"/, '') + '%'}
			tokenize.each do |x|
				if @ids.size != 0
					temp =  category ? ClassRoom.where('lower(name) LIKE ? OR lower(tag_line) LIKE ? OR lower(summary) LIKE ?', x.downcase, x.downcase, x.downcase)
					.where('id NOT IN (?)', @ids).where('category = ?', category)
					:
					ClassRoom.where('lower(name) LIKE ? OR lower(tag_line) LIKE ? OR lower(summary) LIKE ?', x.downcase, x.downcase, x.downcase)
					.where('id NOT IN (?)', @ids)
					temp.each do |x|
						@ids.push(x.id)
					end
					@result += temp
				else
					temp = category ? ClassRoom.where('lower(name) Like ? OR lower(tag_line) LIKE ? OR lower(summary) LIKE ?', x.downcase, x.downcase, x.downcase)
					.where('category = ?', category)
					:
					ClassRoom.where('lower(name) Like ? OR lower(tag_line) LIKE ? OR lower(summary) LIKE ?', x.downcase, x.downcase, x.downcase)
					temp.each do |x|
						@ids.push(x.id)
					end
					@result += temp
				end
			end
			return @result
		end
  end
  
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
  # GET /class_rooms
  # GET /class_rooms.json
  before_filter do |controller|
    store_location unless controller.request.format.json?
  end

  
  def index
    @class_rooms = ClassRoom.all
    @class_rooms = Kaminari.paginate_array(@class_rooms).page(params[:page]).per(15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @class_rooms }
    end
  end
  
  
  def add_user
    @user = current_user
    @user_permission = UserPermission.new(params[:user_permission])
    @class_room = ClassRoom.find(@user_permission.class_room_id)
    if(!is_creator(@class_room) && !UserPermission.where("user_id = ? AND class_room_id = ?", @user.id, @class_room.id).first)
      @user_permission.user_id = @user.id
      @user_permission.permission_type = "student"
      respond_to do |format|
        if @user_permission.save
          format.html { redirect_to class_room_path(@class_room) , notice: 'Class joined successfully!' }
        else
          format.html { redirect_to class_room_path(@class_room) , flash => { :fail => 'Error joining class.' } }
        end
      end
    else
      redirect_to class_room_path(@class_room) , :flash => { :fail => 'You can\'t join a class more than once!' }
    end
  end
  
  def change_active
    #make sure we don't update updated_at when just changing order or publishing
    ClassRoom.record_timestamps = false
    
    @class_room = ClassRoom.find(params[:id])
    if @class_room.active
      @class_room.update_attribute(:active, false)
    else
      @class_room.update_attribute(:active, true)
    end
    
    #Turn timestamps back on    
    ClassRoom.record_timestamps = true
    
    redirect_to class_room_path(@class_room)
  end
  
  def begin_class
    #make sure we don't update updated_at when just changing order or publishing
    ClassRoom.record_timestamps = false
    
    @class_room = ClassRoom.find(params[:id])

    @class_room.started ? @class_room.update_attribute(:started, false) : @class_room.update_attribute(:started, true)

    #Turn timestamps back on    
    ClassRoom.record_timestamps = true
    
    redirect_to class_room_path(@class_room)
  end
  
  def students
    @class_room = ClassRoom.find(params[:id])
    @students = []
    UserPermission.where("class_room_id = ?", @class_room.id).each do |x|
      @students << User.find(x.user_id)
    end      
    set_vars
    render :layout => "layouts/show_class_room", :locals => {:which_tab => "students"}
  end

  # GET /class_rooms/1
  # GET /class_rooms/1.json
  def show
    @class_room = ClassRoom.find(params[:id])
    @announcement = @class_room.announcements.order('created_at DESC').first
    @new_announcement = Announcement.new
    @description = @class_room.resource
    set_vars
      
    respond_to do |format|
      format.html { render :layout => "show_class_room", :locals => {:which_tab => "home"} }
      format.json { render json: @class_room }
    end
  end

  # GET /class_rooms/new
  # GET /class_rooms/new.json
  def new
    require_user
    if current_user
      @class_room = ClassRoom.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @class_room }
      end
    end
  end

  # GET /class_rooms/1/edit
  def edit
		@class_room = ClassRoom.find(params[:id])
		if is_creator(@class_room)
			respond_to do |format|
				format.html 
				format.json { render json: @class_room }
			end
		else
		  flash[:fail] = "You must be the creator to do edit the class."
      redirect_back_or_default @class_room
		end
	end


  # POST /class_rooms
  # POST /class_rooms.json
  def create
    @user = current_user
    @class_room = ClassRoom.new(params[:class_room])
    @class_room.user_id = @user.id
    @class_room.started = false
    @class_room.active = true
    @class_room.tag_line = @class_room.tag_line.upcase
    
    respond_to do |format|
      if @class_room.save
        if @class_room.start_date <= Date.today
          @class_room.update_attribute(:started, true)
        end
        ResourcePage::SECTIONS.each do |type|
          resource_page = ResourcePage.new(:class_room_id => @class_room.id, :section => type.capitalize)
          resource_page.save
          section = Section.new(:resource_page_id => resource_page.id, :order => 0, :title => "All " + type.capitalize)
          section.save
          if type == "materials"
            resource = Resource.new(:name => "Class Description", :user_id => @user.id, :class_room_id => @class_room.id,
              :file_type => "document", :source_call => "materials", :hidden => true, :order => 0, :section_id => section.id)
            resource.save
            document = Document.new(:resource_id => resource.id, :content => "<p>Edit this document with a description of your class!</p>", :parsed_content => "<p>Edit this document with a description of your class!</p>")
            document.save
            @class_room.update_attribute(:description_id, resource.id)
          end
        end
        forum = Forum.new(:class_room_id => @class_room.id)
        forum.save
        format.html { redirect_to @class_room, notice: 'Class was successfully created.' }
        format.json { render json: @class_room, status: :created, location: @class_room }
      else
        format.html { render action: "new" }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /class_rooms/1
  # PUT /class_rooms/1.json
  def update
    @class_room = ClassRoom.find(params[:id])
    if is_creator(@class_room)
      respond_to do |format|
        if @class_room.update_attributes(params[:class_room])
          format.html { redirect_to @class_room, notice: 'Class was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @class_room.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_default @class_room
    end
  end

  # DELETE /class_rooms/1
  # DELETE /class_rooms/1.json
  def destroy
    @user = current_user
    @class_room = ClassRoom.find(params[:id])
    if is_creator(@class_room)
      @class_room.destroy
      
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    else
      redirect_to class_room_path(@class_room), :flash => { :fail => "You do not have permission to modify this class." }
    end
  end

  def plus1
    class_room = ClassRoom.where(:id => params[:id]).first
    rating = class_room.class_room_ratings.where(:user_id => current_user.id).first
    if rating == nil
      rating = ClassRoomRating.new(:user_id => current_user.id, :class_room_id => params[:id], :value => 1)
    elsif rating.value == 0
      rating.value = 1
    elsif rating.value == 1
      rating.value = 0
    else
      rating.value = 1
    end
    rating.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {:rating => rating } }
    end
  end
  
  def minus1
    class_room = ClassRoom.where(:id => params[:id]).first
    rating = class_room.class_room_ratings.where(:user_id => current_user.id).first
    if rating == nil
      rating = ClassRoomRating.new(:user_id => current_user.id, :class_room_id => params[:id], :value => -1)
    elsif rating.value == 0
      rating.value = -1
    elsif rating.value == -1
      rating.value = 0
    else
      rating.value = -1
    end
    rating.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {:rating => rating } }
    end
  end
  
  def search
    @search_term = params[:search_term]
    @category = params[:category]
    @class_rooms = ClassRoom.search(@search_term, (@category && @category != "All") ? @category : nil).sort_by { |class_room| class_room.updated_at }.reverse
    @class_rooms = Kaminari.paginate_array(@class_rooms).page(params[:page]).per(15)
  end
  
  def class_names
    term = "%" + params[:term] + "%"
    @classes = ClassRoom.where("lower(name) LIKE ?", term.downcase).limit(30)
    @classes_hash = []
    @classes.each do |x|
      @classes_hash << {"label" => x.name, "value" => class_room_path(x.id)}
    end
    render :json => @classes_hash
  end
  
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/views/class_rooms/_edit_form.html.haml
= form_for(@class_room) do |f|
  - if @class_room.errors.any?
    #error_explanation.ui-state-error.ui-corner-all
      %h2= "#{pluralize(@class_room.errors.count, "error")} prohibited this class from being created:"
      %ul
      - @class_room.errors.full_messages.each do |msg|
        %li= msg


  .new_class_header
    .field.learn_to_big
      %h3 Step 1: Pick a Tagline
      = f.label :tag_line, "Learn To"
      = f.text_field :tag_line
    .field.summary_big
      %h3 Step 2: Write a Short Description
      = f.label :short_description
      = f.text_area :summary
  .form_page.other_info
    %h3 Step 3: Official Name
    .field
      = f.text_field :name, :class => "text"
    %div{:style => "display: hidden"}
      .field
        = f.label :category, "Category", :class => "main"
        = f.select :category, ClassRoom::CATEGORIES[1..-1], :include_blank => 'Please select one...'
      .field
        = f.label :start_date, :class => "main"
        = f.date_select :start_date
      .field
        = f.label :end_date, :class => "main"
        = f.date_select :end_date
      %div{:style => "display: none"}
        .field
          = f.label :occupancy, "Maximum Enrollment", :class => "main"
          = f.number_field :occupancy, :value => 0, :class => "text"
        .field
          = f.label :price, :class => "main"
          $
          = f.text_field :price, :value => "0.00", :class => "text"
    .actions
      = f.submit "Update your class!"

app/views/class_rooms/_form.html.haml
= form_for(@class_room) do |f|
  - if @class_room.errors.any?
    #error_explanation.ui-state-error.ui-corner-all
      %h2= "#{pluralize(@class_room.errors.count, "error")} prohibited this class from being created:"
      %ul
      - @class_room.errors.full_messages.each do |msg|
        %li= msg

  .new_class_header
    %h3 Step 1: Pick a Tagline
    .field.learn_to_big
      %p.hint{:style => "margin-top: 29px"} What will I learn from your class?  Don't worry about grammar - phrases like "learn to math" are perfectly fine.
      = f.label :tag_line, "Learn To"
      = f.text_field :tag_line
    %h3 Step 2: Write a Short Description
    .field.summary_big
      %p.hint Now that I'm hooked, give me some details about what I should expect.  You could start with a phrase like "This class will cover..." or "This class will teach you how to...".  Don't make it too detailed - you'll get a chance to add more specific information later.
      = f.label :short_description
      = f.text_area :summary
  .form_page.other_info
    %h3 Step 3: Other Info
    .field
      = f.label :name, "Official Name", :class => "main"
      %p.class_create_hint This is the name that will show up for this class when people search.
      = f.text_field :name, :class => "text"
    .field
      = f.label :category, "Category", :class => "main"
      %p.class_create_hint In which category does this class best fit?
      = f.select :category, ClassRoom::CATEGORIES[1..-1], :include_blank => 'Please select one...'
    .field
      = f.label :start_date, :class => "main"
      %p.class_create_hint When are you planning open this class to students?  (Leave it as today's date to start right away!)
      = f.date_select :start_date
    -#
      .field
        = f.label :occupancy, "Maximum Enrollment", :class => "main"
        %p.hint Specify the maximum number of people that can sign up for your class.  Leave it as 0 for unlimited.
        = f.number_field :occupancy, :value => 0, :class => "text"
      .field
        = f.label :price, :class => "main"
        $
        = f.text_field :price, :value => "0.00", :class => "text"
    .actions
      = f.submit "Create your class!"

app/views/class_rooms/_list_display.html.haml
.class_list_item
  .title
    .left
      %h3
        %strong= link_to class_room.name, class_room
    .right
      by #{link_to class_room.user.login, class_room.user}
      in #{class_room.category},
      #{pluralize class_room.users.length, "student"}
  .middle
    Learn To #{class_room.tag_line.split().map{|x| x.capitalize()}.join(" ")}:
    =class_room.summary
      

app/views/class_rooms/edit.html.erb
<%= render 'edit_form' %>

<%= link_to 'Show', @class_room %> 
<%= link_to 'Back', class_room_path(@class_room) %>

app/views/class_rooms/index.html.haml
%h1 Classes

- @class_rooms.each do |class_room|
  =render :partial => "list_display", :locals => {:class_room => class_room}
= paginate @class_rooms

= link_to 'New Class room', new_class_room_path

app/views/class_rooms/new.html.haml
.create_class
  %h1 New Class
  = render 'form'

app/views/class_rooms/search.html.haml
.search_results_page
  = form_tag class_rooms_search_path, :method => "get" do
    .search_field                
      = label_tag :category, "Category:"
      = select_tag :category, options_for_select(ClassRoom::CATEGORIES, params[:category] ? params[:category] : "All")
      &nbsp;
      = label_tag :category, "Search text:"
      = text_field_tag :search_term, "", :class => "text"
      &nbsp;
      = submit_tag "Search", :class => "button"
    %hr
    - if @search_term and @search_term != ""
      %h1
        Search results for 
        %strong #{@search_term}
        -if @category and @category != "" and @category != "All"
          in #{@category}
    - elsif  @category and @category != "" and @category != "All"
      %h1 Listing of classes in #{@category}
    - elsif @category and @category == "All"
      %h1 List of all classes
  - @class_rooms.each do |class_room|
    = render :partial => "list_display", :locals => {:class_room => class_room}
  = paginate @class_rooms
       

app/views/class_rooms/show.html.haml
.class_home
  -if not @class_room.started and not @is_creator
    .class_room_will_start
      -if @class_room.start_date > Date.today
        The teacher has indicated that this class will start on
        ="<strong>#{l @class_room.start_date}</strong>.".html_safe
        Enroll to be notified!
      -else 
        This class hasn't started yet.  Enroll to be notified when it begins!
  -if not @class_room.started and @is_creator
    .class_room_start_bar.ui-state-highlight.ui-corner-all
      = link_to "Begin class!", begin_path(@class_room), :class => "button", :style => "float: right; margin-top: -5px;"
      %h3
        Class Hidden
      .hidden_explanation.no_javascript
        %p
          Class materials are currently hidden from students because the class hasn't started.  
          You specified that the class will start on 
          ="<strong>#{l @class_room.start_date}</strong>.".html_safe
        %p Click the button to start the class and make the materials public.

  .rating_container
    .up-down-widget
      - if @permission_type == "student"
        - rbu = @class_room.rating_by_user(current_user.id)
        = link_to "+", class_rooms_plus1_path(@class_room), :method => :post, :class => "udw-top" + (rbu==1 ? " active" : "")
        %span.udw-middle= @class_room.rating
        = link_to "-", class_rooms_minus1_path(@class_room), :method => :post, :class => "udw-bottom" + (rbu==-1 ? " active" : "")
  
  %h1
    %span.learn_to Learn To
    - size = [7-@class_room.tag_line.length/7, 3].max
    %span.tag_line{:style => "font-size: #{size}em"}= @class_room.tag_line.upcase

  
  %h2
    = @class_room.summary
  .below_tagline
    .info
      Taught by #{link_to @class_room.user.login, @class_room.user}, #{pluralize @class_room.users.length, "student"} enrolled
  -if @announcement or @is_creator 
    .announcements_box
      %h4
        = "Most Recent Announcement"
        - if current_user
          = link_to "see all",  class_room_announcements_path(@class_room)
        - if @is_creator
          %a{:href=>"#", :id => "post_new"} post new
      .new_announcement_form
        -if @is_creator
          %h4 Editing New Announcement
          = render :partial => 'announcements/new_announcement', :locals => {:class_room => @class_room}
      -if @announcement
        .announcement
          %h3= @announcement.title
          %p= @announcement.content
          .bottom #{time_ago_in_words @announcement.created_at} ago by #{link_to @announcement.user.login, @announcement.user}
      -elsif @is_creator
        .placeholder
          No announcements yet!  Click 'post new' above to make an announcement.
    
  - if @class_room.resource && (!@class_room.resource.hidden || @is_creator)
    %hr{:style => (@announcement or @is_creator ? "" : "margin-top: 30px")}
    %div
      - if @is_creator
        = link_to "Edit Class Description", edit_class_room_resource_page_section_resource_path(@description.section.resource_page.class_room, @description.section.resource_page, @description.section, @description.id), :id => "edit_class_description"
        = link_to @description.hidden ? "Show Class Description To Students" : "Hide Class Description From Students", class_room_resource_page_section_publish_path(@description.section.resource_page.class_room, @description.section.resource_page, @description.section, @description.id), :class => "hide_link"
      = render :partial => "shared/document_embed", :locals => { :res => @class_room.resource, :style => "big_embed" }

app/views/class_rooms/students.html.haml
%h2{:style => "font-size: 2.5em"} Students
- if @students.length > 0
  - @students.each do |student|
    .student_list_item
      %h4
        = link_to student.login, user_path(student)
- else
  %p{:style => "margin: 10px 0; color: #555"} No students yet!