config/routes.rb
Classroom::Application.routes.draw do

  match "class_rooms/:id/plus1" => "class_rooms#plus1", :as => :class_rooms_plus1, :via => :post
  
  match "class_rooms/:id/minus1" => "class_rooms#minus1", :as => :class_rooms_minus1, :via => :post

  get "class_rooms/class_names"
  
  get "students/show"
 
  get "class_rooms/search"

  match '/auth/:provider/callback' => 'authentications#create'

  get "authentications/index"

  get "authentications/create"

  get "authentications/destroy"

  match 'activate(/:activation_code)' => "activations#create", :as => :activate_account
 
  get "users/edit_password"
  
  get "users/resend_activation"
  
  resources :password_resets
  
  match 'password_resets/:id/please_register' => "password_resets#please_register", :as => :resend
  
  resources :users do
    match 'notifications/count' => 'notifications#count'
    resources :notifications
  end

  post "class_rooms/add_user"
  
  get "class_rooms/del_user"
  
  resources :user_permissions
  
  match 'class_rooms/:id/students' => "class_rooms#students", :as => :class_room_students

  resources :class_rooms do
    resources :premium_classes
    resources :announcements do
    end
    resources :resource_pages do
      resources :sections do
        resources :resources do
          resources :resource_comments
          match 'documents/:id/create_doc_rec' => "documents#create_doc_rec", :as => :doc_rec, :via => :post
        end
        match 'resources/:id/change_hidden' => "resources#change_hidden", :as => :publish
        match 'resources/:id/change_completed' => "resources#change_completed", :as => :completed
        match 'resources/:id/change_order' => "resources#change_order", :as => :rearrange
      end
      match 'sections/:id/change_order' => "sections#change_order", :as => :rearrange
      match 'sections/:id/update' => "sections#update", :as => :update, :via => :post
    end
    match 'forums/:id/search_by_tag' => "forums#search_by_tag", :as => :search_by_tag, :via => :get 
    match 'forums/:id/search' => "forums#search", :as => :search, :via => :get 
    resources :forums do
      resources :posts do
        match "comments/:id/plus1" => "comments#plus1", :as => :comments_plus1, :via => :post
        match "comments/:id/minus1" => "comments#minus1", :as => :comments_minus1, :via => :post
        resources :comments do
          resources :subcomments
        end
      end
    end
  end
  
  match 'class_rooms/:id/change_active' => "class_rooms#change_active", :as => :activate
  match 'class_rooms/:id/begin_class' => "class_rooms#begin_class", :as => :begin
  
  resources :authentications

  

  get "user_sessions/new"
  
  get "user_sessions/new_ajax"
  
  get "home/teacher_index"
  
  get "home/index"
  
  get "home/manage"

  get "home/please_register"

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'login_ajax' => "user_sessions#new_ajax",      :as => :login_ajax
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  get "auth/facebook"
 
  resources :pages, :only => :show

  root :to => 'home#index'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :store_location

  def index
    @posts = []
    @announcements = []
    @resources = []
    
  	if current_user
			if ClassRoom.exists?(1)	
				@class_room = ClassRoom.find(1)
				unless @class_room && @class_room.user.email == "jtwarren@mit.edu"
				  @class_room = nil
				end
			end	
			
  	  @ids = current_user.class_rooms.map { |x|  x.id }
  	  @news_feed_posts = []
  	  @posts = []
  	  if @ids.size > 0
    	  @news_feed_posts = Resource.where(:class_room_id => @ids).order('created_at DESC').where(:hidden => "false").limit(20).map do |resource|
            { :resource => resource,
              :type => "resource",
              :created_at => resource.created_at }
          end
        @news_feed_posts += Announcement.where(:class_room_id => @ids).order('created_at DESC').limit(20).map do |announcement|
            { :announcement => announcement,
              :type => "announcement",
              :created_at => announcement.created_at }
          end
    	  @posts = Post.where(:forum_id => @ids).order('created_at DESC').limit(10)
    		@news_feed_posts.sort_by! { |x| x[:created_at]}.reverse!.first(20)
      end
      @random_class_room = random
      render :action => "user_index", :layout => "layouts/user_home", :locals => {:which_tab => "user_index"}
    #There is no user logged in
    else
      @features = PremiumClass.first(4).sort_by { |x| x.created_at }.reverse
      render :action => "index"
      return
    end
  end        

  def teacher_index
    activity_by_user_and_class_id(1,1)
    @posts = []
    @announcements = []
    @resources = []
    
    if current_user
      @ids = current_user.taught_classes.map { |x|  x.id if x.active }
      @news_feed_posts = []
      @posts = []
      if @ids.size > 0
        @posts = Post.where(:forum_id => @ids).order('created_at DESC').limit(10)
      end
      @posts.sort_by! { |post| post.created_at}.reverse!.first(10)
  		@news_feed_posts.sort_by { |post| post[:created_at]}.reverse!  
      render :action => "teacher_index", :layout => "layouts/user_home", :locals => {:which_tab => "teacher_index"}
      @random_class_room = random
    else
      render :action => "index"
      return
    end
  end
  
  def manage
    @class_rooms = current_user.class_rooms
    @taught_classes = current_user.taught_classes
    render :action => "manage", :layout => "layouts/user_home", :locals => {:which_tab => "manage"}
  end

  def please_register
  
  end

  def media_test
  	if current_user
  		@user = current_user
  	end
  end
  
  def random
    @ids = []
    if current_user
      @cur_ids = current_user.class_rooms.map { |x|  x.id }
      @ids = ClassRoom.select(:id).where("id NOT IN (?)", @cur_ids).map { |x| x.id }
    else
      @ids = ClassRoom.select(:id).map { |x| x.id }
    end
    return ClassRoom.where(:id => @ids.sample).first
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def get_top_three(recs)
    i = 0
    j = 0
    resources = []
    until (i > 2 || j >= recs.length)
      rec = recs[j]
      unless rec.hidden
        section = rec.section
        page = section.resource_page
        class_room = page.class_room
        resources << [rec, [class_room, page, section, rec]]
        i+=1
      end
      j+=1
    end
    return resources
  end

end

app/views/home/index.html.haml
.display_case
  .img_container
    - @features.each_with_index do |feature, index|
      = image_tag feature.image(:full_width), :id => "img_" +  index.to_s

  %ul.featured_class_tabs
    - @features.each_with_index do |feature, index|
      %li{:class => (index == 0 ? "active" : ""), :id => "tab_" + index.to_s}
        .mini_tagline
          .learn_to
            Learn To
          - size = [7-feature.class_room.tag_line.length/7, 4].max*0.3
          .text{:style => "font-size: #{size}em"}
            =feature.class_room.tag_line

.info_container
  - @features.each_with_index do |feature, index|
    %div.featured_class_info{:id => "class_" + index.to_s, :style => (index == 0?"":"display: none;")}
      .featured_when Featured This Week
      %h3 #{link_to feature.class_room.name, feature.class_room}, taught by #{feature.class_room.user.login}
      %p= feature.class_room.summary

%hr

.info_section
  %h3 LearnTo is a platform for anyone to teach an online class, on any topic.
  %p We want to create a community of learning where people can share their knowledge in the form of structured online classes.  Everyone is an expert on something, be it playing Starcraft, counting cards, designing websites, composing music, or writing poems.  We want to encourage people to share their insights about the world so that their experience may benefit others.
  %p Sign in and join a class to see what it's all about.

app/views/home/manage.html.haml
- content_for :center_column do
  - if @taught_classes.size > 0
    = "Classes you are teaching"
    %p
      -@taught_classes.each do |taught_class|
        = link_to taught_class.name, class_room_path(taught_class)
        = link_to "delete", taught_class, :method => :delete, :confirm => "Are you sure you want to destroy this class and all of its contents?"
        %p
          = taught_class.summary
        %p
          - if taught_class.users.size == 1
            = "There is "
          - else
            = "There are "
          = link_to pluralize(taught_class.users.size, "student"), students_show_path(:class_room => taught_class.id)
          = " enrolled in this class"
          
  - if @class_rooms.size > 0 
    = "Classes you are taking"
    %p
    -@class_rooms.each do |class_room|
      -if class_room
        %p
          - @user_permission = UserPermission.where(:user_id => current_user.id, :class_room_id => class_room.id).first
          = link_to class_room.name, class_room_path(class_room.id)
          = link_to "leave class", class_rooms_del_user_path(:perm_id => @user_permission.id), :confirm => "Are you sure you want to leave this class?"
          %p
            = class_room.summary
          %p
            - if class_room.users.size == 1
              = "There is "
            - else
              = "There are "
            = link_to pluralize(class_room.users.size, "student"), students_show_path(:class_room => class_room.id)
            = " enrolled in this class"

app/views/home/please_register.html.haml
%div{:style=>"position: relative;"}
  %div{ :style => "position: absolute; top: 160px; left: 30px; width: 240px; padding: 10px; font-size: 1.2em; color: #444; background: #fff; border: 1px solid #999; border-radius: 5px; -moz-border-radius: 5px;"}
    Please check your email for account activation instructions.
    %br
    %br
    You should receive a link that will allow you to sign in.
    = link_to 'Click here', users_resend_activation_path(:email => @user.email)
    to resend the activation email.
  %div{ :style => "background: url(/assets/email.jpg); width: 100%; height: 600px;"}

app/views/home/please_reset_password.html.haml
%div{:style=>"position: relative;"}
  %div{ :style => "position: absolute; top: 160px; left: 30px; width: 240px; padding: 10px; font-size: 1.2em; color: #444; background: #fff; border: 1px solid #999; border-radius: 5px; -moz-border-radius: 5px;"}
    Please check your email for password reset instructions.
    %br
    %br
    If problems persist, please try again to make sure you used the correct email or register with facebook.
  %div{ :style => "background: url(/assets/email.jpg); width: 100%; height: 600px;"}

app/views/home/teacher_index.html.haml
-content_for :right_column do  
  .news_feed
    %h1 Your Classes
    - current_user.taught_classes.each do |class_room|
      .teacher_feed_class
        - resource_pages = class_room.resource_pages.sort_by {|x| x.id}
        %h3= link_to class_room.name, class_room_path(class_room)
        .info #{pluralize class_room.users.length, "student"}
        .section_links
          %h4 Quick Links
          %ul
            %li= link_to "Lessons", class_room_resource_page_path(class_room, resource_pages[0])
            %li= link_to "Homework", class_room_resource_page_path(class_room, resource_pages[1])
            %li= link_to "Materials", class_room_resource_page_path(class_room, resource_pages[2])
            %li= link_to "Tests/Quizzes", class_room_resource_page_path(class_room, resource_pages[3])
            %li= link_to "Discussion", [class_room, class_room.forum]
            %li= link_to "Students", students_show_path(:class_room => class_room.id)
        .clear 
  
- content_for :center_column do
  .new_posts.teacher_post_feed
    %h3
      Recent Discussion Posts in your Classes
    - @posts.each do |post|
      .feed_forum_post  
        %h4
          = link_to post.title, class_room_forum_post_path(post.forum.class_room, post.forum, post)
          in #{ link_to post.forum.class_room.name, class_room_path(post.forum.class_room.id)}
        - tokens = post.content.split()
        %p{:style => "margin: 5px 0"}
          - num_words = 40
          = tokens.first((tokens.length > num_words*2) ? num_words : num_words*2).join(" ")
          - if tokens.length > num_words*2
            = link_to "more...", class_room_forum_post_path(post.forum.class_room, post.forum, post), :class => "more_link"
            %span.more= tokens[num_words..-1].join(" ")
        %div.bottom
          #{link_to post.user.login, post.user}
          #{ time_ago_in_words(post.created_at, include_seconds = true)} ago

app/views/home/user_index.html.haml
- content_for :right_column do
  .new_posts
    %h3 New Discussion Posts
    - @posts.each do |post|
      .feed_forum_post
        %h4
          = link_to post.title, class_room_forum_post_path(post.forum.class_room, post.forum, post)
        %div.bottom
          #{link_to post.user.login, post.user}
          in #{ link_to post.forum.class_room.name, class_room_path(post.forum.class_room.id)}
          #{ time_ago_in_words(post.created_at, include_seconds = true)} ago
        
- content_for :center_column do
  .news_feed
    %h1 Class Updates
    %ul
      - if current_user.class_rooms.length < 1
        .empty_news_feed
          %h2 You're not in any classes yet!
          -if @class_room
            Check out our tutorial class:
            %ul
              = link_to "Learn to #{@class_room.tag_line}!", class_room_path(@class_room)
          
          = @class_room ? "Or pick " : "Pick "
          a category you're interested in to browse classes:
          %ul 
            - ClassRoom::CATEGORIES.each do |category|
              %li
                =link_to category, class_rooms_search_path( { "category" => category, "search_term" => ""} )
      - elsif @news_feed_posts.empty?
        .empty_news_feed
          %h2 There's nothing to see in any of your classes!
          -if @class_room
            Check out our tutorial class:
            %ul
              = link_to "Learn to use this site!", class_room_path(@class_room)
          
          = @class_room ? "Or pick " : "Pick "
          a category you're interested in to browse classes:
          %ul 
            - ClassRoom::CATEGORIES.each do |category|
              %li
                =link_to category, class_rooms_search_path( { "category" => category, "search_term" => ""} )
      -else
        - @news_feed_posts.each do |post|
          - if post[:type] == "resource"
            %li.news_feed_item
              - resource = post[:resource]
              - announcement = post[:resource]
              - section = resource.section
              - resource_page = section.resource_page
              - class_room = resource_page.class_room
              %h3 
                =(resource.created_at == resource.updated_at ? "New" : "Updated")
                #{resource_page.section.singularize.downcase} in
                = link_to class_room.name, class_room
              %h4
                = link_to resource.name, [class_room, resource_page, section, resource]
              - if resource.caption != ""
                %p= resource.caption
              .bottom
                posted by #{link_to resource.user.login, resource.user} #{time_ago_in_words resource.created_at} ago
          - elsif post[:type] == "announcement"
            %li.news_feed_item
              - announcement = post[:announcement]
              %h3
                New announcement in 
                = link_to announcement.class_room.name, class_room_path(announcement.class_room.id)
              %h4= link_to announcement.title, class_room_announcements_path(announcement.class_room)
              %p= announcement.content
              %div.bottom
                posted by #{link_to announcement.user.login, announcement.user} #{ time_ago_in_words(announcement.created_at.to_time, include_seconds = true)} ago
            