config/routes.rb
Classroom::Application.routes.draw do

  match "class_rooms/:id/plus1" => "class_rooms#plus1", :as => :class_rooms_plus1, :via => :post
  
  match "class_rooms/:id/minus1" => "class_rooms#minus1", :as => :class_rooms_minus1, :via => :post

  get "class_rooms/class_names"
  
  get "students/show"
 
  get "class_rooms/search"

  match '/auth/:provider/callback' => 'authentications#create'

  get "authentications/index"

  get "authentications/create"

  get "authentications/destroy"

  match 'activate(/:activation_code)' => "activations#create", :as => :activate_account
 
  get "users/edit_password"
  
  get "users/resend_activation"
  
  resources :password_resets
  
  match 'password_resets/:id/please_register' => "password_resets#please_register", :as => :resend
  
  resources :users do
    match 'notifications/count' => 'notifications#count'
    resources :notifications
  end

  post "class_rooms/add_user"
  
  get "class_rooms/del_user"
  
  resources :user_permissions
  
  match 'class_rooms/:id/students' => "class_rooms#students", :as => :class_room_students

  resources :class_rooms do
    resources :premium_classes
    resources :announcements do
    end
    resources :resource_pages do
      resources :sections do
        resources :resources do
          resources :resource_comments
          match 'documents/:id/create_doc_rec' => "documents#create_doc_rec", :as => :doc_rec, :via => :post
        end
        match 'resources/:id/change_hidden' => "resources#change_hidden", :as => :publish
        match 'resources/:id/change_completed' => "resources#change_completed", :as => :completed
        match 'resources/:id/change_order' => "resources#change_order", :as => :rearrange
      end
      match 'sections/:id/change_order' => "sections#change_order", :as => :rearrange
      match 'sections/:id/update' => "sections#update", :as => :update, :via => :post
    end
    match 'forums/:id/search_by_tag' => "forums#search_by_tag", :as => :search_by_tag, :via => :get 
    match 'forums/:id/search' => "forums#search", :as => :search, :via => :get 
    resources :forums do
      resources :posts do
        match "comments/:id/plus1" => "comments#plus1", :as => :comments_plus1, :via => :post
        match "comments/:id/minus1" => "comments#minus1", :as => :comments_minus1, :via => :post
        resources :comments do
          resources :subcomments
        end
      end
    end
  end
  
  match 'class_rooms/:id/change_active' => "class_rooms#change_active", :as => :activate
  match 'class_rooms/:id/begin_class' => "class_rooms#begin_class", :as => :begin
  
  resources :authentications

  

  get "user_sessions/new"
  
  get "user_sessions/new_ajax"
  
  get "home/teacher_index"
  
  get "home/index"
  
  get "home/manage"

  get "home/please_register"

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'login_ajax' => "user_sessions#new_ajax",      :as => :login_ajax
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  get "auth/facebook"
 
  resources :pages, :only => :show

  root :to => 'home#index'

  

end

app/views/resources/_edit_form.html.haml
= form_for [@class_room, @resource_page, @section, @resource] do |f|
  - if @resource.errors.any?
    #error_explanation
      %h2= "#{pluralize(@class_room.errors.count, "error")} prohibited this class_room from being saved:"
      %ul
      - @resource.errors.full_messages.each do |msg|
        %li= msg
        
  .field
    = f.label :name, :class => "main"
    = f.text_field :name, :class => "text"
  .field
    = f.label :caption, :class => "main"
    = f.text_field :caption, :class => "text"
  .field
    = f.label "Hidden from students", :class => "main"
    %p.hint Use this to keep drafts that you aren't ready to post yet.
    = f.check_box :hidden

  %br

  .actions
    = f.submit "Save", :class => "button"
    - if @resource != @class_room.resource
      = link_to 'Delete', class_room_resource_page_section_resource_path(@class_room, @resource_page, @section, @resource), confirm: 'Are you sure?', method: :delete, :class => "button"

    %span.button#insert_link Insert Internet Media
    %span.button#insert_file Upload File From Computer
    %span.button#insert_code Insert Code

    #insert_code_form{:title => "Paste Code Here", :style => "display: none"}
      %textarea{:style => "width: 98%; font-family: monospace", :rows => "10"}
      %button Insert
    #insert_link_form{:title => "Paste Link Here", :style => "display: none"}
      %p We support embedding of video from YouTube and Vimeo and images from any source.
      %input{:style => "width: 100%"}
      %button Embed

  - if @resource.file_type == "document"
    .field
      = text_area :document, :content, :id => "tinymce_area", :class => "tinymce"
    = link_to "put embedded resource", class_room_resource_page_section_resource_doc_rec_path(@class_room, @resource_page, @section, @resource, @document), :method => 'post', :id => "link_to_embed_in_document", :style => "display: none"

app/views/resources/_form.html.haml
= form_for [@class_room, @resource_page, @sections.first, @resource] do |f|

  .field
    = label_tag :resource, :Section, :class => "main"
    = collection_select(:section, :id, @sections, :id, :title)
  .field
    = f.label :name, :class => "main"
    = f.text_field :name, :class => "text"
  .field
    = f.label :caption, :class => "main"
    = f.text_field :caption, :class => "text"
  .field
    = f.label :type, "Content Type", :class => "main"
    .type_radio_buttons
      = Resource::TYPES.map { |type| (f.radio_button :file_type, type, :value => type) + (label_tag "resource_file_type_" + type, type) }.join.html_safe
  .field#upload_tab_contents
    = f.label :file, "Upload File", :class => "main"
    = f.file_field :file
  .field#link_tab_contents
    = f.label :url, "Paste URL Here", :class => "main"
    = f.text_field :url, :class => "text"
  .field#document_tab_contents

  %hr

  .actions
    = f.submit "Save", :class => "button"
    - if @resource != @class_room.resource && @resource.id
      = link_to 'Delete', class_room_resource_page_section_resource_path(@class_room, @resource_page, @section, @resource), confirm: "Are you sure you want to delete this #{@resource_page.section.singularize.downcase}?", method: :delete, :class => "button", :style => "float: right"

app/views/resources/edit.html.haml
-if @resource.hidden
  .flash.ui-corner-all.ui-state-highlight
    This document is hidden.  You'll need to publish it after editing so people can see it.

.form_page
  %h1  Editing #{@resource_page.section.singularize}
  %p.hint Located at: #{@section.title} #{">"} #{@resource.name} 

  %hr
  - if @resource.file_type == "document"
    = render 'edit_form'
  - else
    = render 'form',
          :locals => { :resource => @resource, :resource_page => @resource_page, :section => @section, 
          :class_room => @class_room, :sections => @sections,
          :style => "small_resource_form" }

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Caption</th>
    <th>Url</th>
    <th>Type</th>
    <th>Uploader</th>
    <th>Class room</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.caption %></td>
    <td><%= resource.url %></td>
    <td><%= resource.type %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.haml
.resource_show_page
  - if @is_creator
    .actions
      = link_to @resource.hidden ? "Publish To #{@resource_page.section}": "Hide From #{@resource_page.section} Page", class_room_resource_page_section_publish_path(@class_room, @resource_page, @section, @resource), :class => "button"
      = link_to 'Edit', edit_class_room_resource_page_section_resource_path(@class_room, @resource_page, @section, @resource),
       :class => "button"
      - if @resource != @class_room.resource
        = link_to 'Delete', class_room_resource_page_section_resource_path(@class_room, @resource_page, @section, @resource), confirm: 'Are you sure?', method: :delete, :class => "button"
  
  -if @resource_page.section.downcase == "homework" and not @is_creator
    = @resource.users.include?(current_user) ? "Congratulations, you've finished this assignment." : "Mark this assignment as completed after you've finished."
    = link_to 'Toggle completed', class_room_resource_page_section_completed_path(@class_room, @resource_page, @section, @resource)

  .info
    %div #{link_to @resource_page.section.capitalize, [@class_room, @resource_page]} #{">"} #{@section.title} #{">"} #{@resource.name}
  - if @resource.hidden
    .ui-state-highlight.ui-corner-all.flash This #{@resource_page.section.singularize.downcase} is hidden.  Click publish above to make it visible.
      
  = render :partial => "shared/embed", :locals => {:res => @resource, :info => @resource.get_info, :style => "full_page", :hidden => false}

.resource_sub_comments
  %h3 #{pluralize @resource_comments.length, "comment"}
  - @resource_comments.each do |comment|
    = render :partial => "resource_comments/resource_comment", :locals => {:resource_comment => comment}
  = render :partial => "resource_comments/new_resource_comment"
  


-#
  :javascript
    $( function(){ 
    jtv_api.new_player( "stream_box",
    {
      channel: "djmashko",
      //stream_key: "live_23830113_38mnbJR22bRomDPk2AxKjxXpPCXw14",
      consumer_key: "jjCZcGGsUENc4vAX5ODwA",
      auto_play: true
    });
      
    var jtv = document.getElementById("stream_box"); 
    function setStartingSize() { 
      if (jtv.children.length == 0) { 
        setTimeout(setStartingSize, 1000); 
        return; 
      } 
      var player = jtv.children[0]; 
      jtv.removeChild(player); 
      player.type = 'application/x-shockwave-flash'; 
      jtv.appendChild(player); 
      player.height = 450; 
      player.width = 600; 
    } 
    setStartingSize(); 
  
  });
  %div{:style => "text-align: center"}
    #stream_box{:style=>"float:left"}
    %iframe{:src => "http://www.justin.tv/chat/embed?channel=djmashko", :style=>"float:left", :width => 340, :height => 450}
    .clear 